In [15]:
import pandas as pd

arome = pd.read_csv("../data/cleaned/Arome_clean_final.csv", dtype={"id": str})
metar = pd.read_csv("../data/raw/METAR_2021_2025.csv", dtype={"station": str}, low_memory=False)
mapping = pd.read_csv("../data/cleaned/isd_history_station_check.csv", dtype=str)

arome["datetime"] = pd.to_datetime(arome["datetime"].astype(str), format="%Y%m%d%H")

metar["valid"] = pd.to_datetime(metar["valid"])
metar["datetime"] = metar["valid"].dt.floor("h")

icao_to_wmo = dict(zip(mapping["icao"], mapping["id"]))
metar["wmo_id"] = metar["station"].map(icao_to_wmo)

In [16]:
print(arome["id"].nunique())
print(metar["wmo_id"].nunique())
print(sorted(arome["id"].unique()))
print(sorted(metar["wmo_id"].dropna().unique()))

26
20
['60033', '60060', '60096', '60101', '60107', '60115', '60120', '60135', '60136', '60141', '60150', '60155', '60156', '60160', '60191', '60200', '60210', '60220', '60230', '60250', '60252', '60265', '60280', '60285', '60338', '60340']
['60033', '60101', '60107', '60115', '60135', '60141', '60150', '60155', '60156', '60191', '60200', '60210', '60220', '60230', '60252', '60265', '60280', '60285', '60338', '60340']

In [17]:
print(arome["datetime"].min(), arome["datetime"].max())
print(metar["datetime"].min(), metar["datetime"].max())

2019-01-01 21:00:00 2025-12-31 23:00:00
2021-01-01 00:00:00 2025-12-30 23:00:00

In [19]:
set(arome["id"]) - set(metar["wmo_id"].dropna())

{'60060', '60096', '60120', '60136', '60160', '60250'}

In [20]:
mapping[mapping["id"].isin(["60060","60096","60120","60136","60160","60250"])]

,id,found,coord_match,icao,station_name,lat_arome,lon_arome,lat_isd,lon_isd,begin,end
1,60060,True,True,GMMF,SIDI IFNI,29.35,-10.175,29.369,-10.18,19500310,20250824
2,60096,True,True,GSVO,VILLA CISNEROS(MIL),23.7,-15.85,23.7,-15.867,19310103,20250404
6,60120,True,True,GMMP,KENITRA (RMAFB),34.3,-6.6,34.3,-6.6,19490122,20250824
8,60136,True,True,GMSL,SIDI SLIMANE,34.225,-6.05,34.233,-6.05,19510901,20210612
13,60160,True,True,GMFI,IFRANE,33.5,-5.15,33.505,-5.153,19490209,19971221
19,60250,True,True,GMAA,INEZGANE,30.375,-9.55,30.381,-9.546,19450615,20250824

In [21]:
missing_icao = ["GMMF", "GSVO", "GMMP", "GMSL", "GMFI", "GMAA"]

metar[metar["station"].isin(missing_icao)]["station"].value_counts()

Series([], Name: count, dtype: int64)

In [22]:
sorted(metar["station"].unique())

['GEML',
 'GMAD',
 'GMAG',
 'GMAT',
 'GMFB',
 'GMFF',
 'GMFK',
 'GMFM',
 'GMFO',
 'GMMC',
 'GMMD',
 'GMME',
 'GMMI',
 'GMML',
 'GMMN',
 'GMMW',
 'GMMX',
 'GMMZ',
 'GMTA',
 'GMTT']

In [23]:
len(metar["station"].unique())

20

In [26]:
mapping[["icao", "id"]]

    icao     id
0   GMML  60033
1   GMMF  60060
2   GSVO  60096
3   GMTT  60101
4   GMTA  60107
5   GMFO  60115
6   GMMP  60120
7   GMME  60135
8   GMSL  60136
9   GMFF  60141
10  GMFM  60150
11  GMMC  60155
12  GMMN  60156
13  GMFI  60160
14  GMMD  60191
15  GMFB  60200
16  GMFK  60210
17  GMMI  60220
18  GMMX  60230
19  GMAA  60250
20  GMAD  60252
21  GMMZ  60265
22  GMAG  60280
23  GMAT  60285
24  GEML  60338
25  GMMW  60340